### ISSUE TITLE
CSV not working

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-dedupe#116]
Creating test data:
![image](https://user-images.githubusercontent.com/47790868/74268947-b44ed900-4cd6-11ea-922d-0cb23c5065e7.png)

**Comment by jakub-bao** [comment]
![image](https://user-images.githubusercontent.com/47790868/74269046-e2341d80-4cd6-11ea-9d8f-99075624027e.png)

**Comment by jakub-bao** [comment]
Issue:

```
{
"httpStatus": "Conflict",
"httpStatusCode": 409,
"status": "ERROR",
"message": "SQL query contains variables which were not provided in request: [dt, rs, ps, dg, pe, ty, ou, ag, pg]"
}
```

**Comment by jakub-bao** [comment]
trying to run locally so i can quickly resolve this however running into this issue with my local setting:

```
Error: API call timed out
    at Function.Error.create (/home/jake/DEV/datim-dedupe/node_modules/simple-errors/index.js:25:11)
    at Function.Error.http (/home/jake/DEV/datim-dedupe/node_modules/simple-errors/index.js:68:21)
    at unhandledApiError (/home/jake/DEV/datim-dedupe/node_modules/express-request-proxy/lib/proxy.js:265:25)
    at Request.<anonymous> (/home/jake/DEV/datim-dedupe/node_modules/express-request-proxy/lib/proxy.js:97:7)
    at Request.emit (events.js:198:13)
    at ClientRequest.<anonymous> (/home/jake/DEV/datim-dedupe/node_modules/request/request.js:819:16)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.emitRequestTimeout (_http_client.js:662:40)
    at Object.onceWrapper (events.js:286:20)
```

have to raise a limit there

**Comment by benguaraldi** [comment]
OBE with new app.
